BEGIN;

CREATE TABLE IF NOT EXISTS T_ORDER
(
    ID                 BIGSERIAL PRIMARY KEY,
    UUID               VARCHAR(255) NOT NULL,
    USERNAME           VARCHAR(255) NOT NULL,
    STATUS             VARCHAR(255) NOT NULL,
    ORDER_DETAIL       TEXT,
    TOTAL_AMOUNT       NUMERIC(19, 4),
    CREATED_BY         VARCHAR(255),
    CREATED_DATE       TIMESTAMP(6),
    LAST_MODIFIED_BY   VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP(6)
);

CREATE INDEX ORDER_UUID_ID_INDEX
    ON T_ORDER (UUID, ID);

CREATE INDEX ORDER_USERNAME_ID_INDEX
    ON T_ORDER (USERNAME, ID);

COMMIT;